#include "lll_internals.h"
#include "mlll_internals.h"
#include "quaternion_tests.h"

#include <stdint.h>
#include <stdio.h>

#if defined(SQISIGN_ML2_PROFILE)
#include <pthread.h>
#endif

#define ML2_TEST_MAX_GENERATORS 16

static const int32_t ML2_TEST_D8_COEFFICIENTS[8][4] = {
    { 6, 0, 0, 0 },
    { 0, 10, 0, 0 },
    { 0, 0, 14, 0 },
    { 0, 0, 0, 22 },
    { 1, 1, 0, 0 },
    { 0, 1, 1, 0 },
    { 0, 0, 1, 1 },
    { 1, 0, 1, -1 },
};

static int ml2_test_vector_arrays_identical(const ibz_vec_4_t *a,
                                            const ibz_vec_4_t *b,
                                            int count);

static void
ml2_test_set_target_hnf(ibz_mat_4x4_t *target)
{
    static const int32_t entries[4][4] = {
        { 11, 3, 7, 2 },
        { 0, 9, 4, 1 },
        { 0, 0, 5, 2 },
        { 0, 0, 0, 7 },
    };

    for (int row = 0; row < 4; row++)
        for (int col = 0; col < 4; col++)
            ibz_set(&(*target)[row][col], entries[row][col]);
}

static void
ml2_test_set_generator(ibz_vec_4_t *generator,
                       const ibz_mat_4x4_t *target,
                       const int32_t coefficients[4])
{
    ibz_t coefficient, term;
    ibz_init(&coefficient);
    ibz_init(&term);

    for (int row = 0; row < 4; row++) {
        ibz_set(&(*generator)[row], 0);
        for (int col = 0; col < 4; col++) {
            ibz_set(&coefficient, coefficients[col]);
            ibz_mul(&term, &(*target)[row][col], &coefficient);
            ibz_add(&(*generator)[row], &(*generator)[row], &term);
        }
    }

    ibz_finalize(&coefficient);
    ibz_finalize(&term);
}

/* Compare the Z-span returned by ML2 with an exact, canonical HNF.
 *
 * The first four generators in each fixture are independent.  Their
 * determinant is a valid HNF modulus: the lattice generated by all d vectors
 * contains the lattice generated by this four-vector subset, so the former
 * index divides the latter index. */
static int
ml2_test_span_matches_hnf(const char *name,
                          const ibz_vec_4_t *generators,
                          int d,
                          const ibz_mat_4x4_t *target_hnf)
{
    int failed = 0;
    int rho;
    int retry_rho;
    quat_alg_t alg;
    ibz_t modulus, actual_det;
    ibz_vec_4_t reduced[4], retried[4];
    ibz_mat_4x4_t independent, expected_hnf;
    quat_lattice_t actual;

    ibz_init(&modulus);
    ibz_init(&actual_det);
    quat_alg_init_set_ui(&alg, 367);
    ibz_mat_4x4_init(&independent);
    ibz_mat_4x4_init(&expected_hnf);
    quat_lattice_init(&actual);
    for (int i = 0; i < 4; i++) {
        ibz_vec_4_init(&reduced[i]);
        ibz_vec_4_init(&retried[i]);
    }

    for (int col = 0; col < 4; col++)
        for (int row = 0; row < 4; row++)
            ibz_copy(&independent[row][col], &generators[col][row]);

    ibz_mat_4x4_inv_with_det_as_denom(NULL, &modulus, &independent);
    ibz_abs(&modulus, &modulus);
    if (ibz_is_zero(&modulus)) {
        printf("[%s] FAIL: oracle subset is not full rank\n", name);
        failed = 1;
        goto cleanup;
    }

    ibz_mat_4xn_hnf_mod_core(&expected_hnf, d, generators, &modulus);
    if (!ibz_mat_4x4_equal(&expected_hnf, target_hnf)) {
        printf("[%s] FAIL: fixture does not span the intended target lattice\n", name);
        failed = 1;
        goto cleanup;
    }

    rho = quat_ml2(reduced, 4, generators, d, &alg);
    if (rho != 4) {
        printf("[%s] FAIL: expected rho=4, got rho=%d\n", name, rho);
        failed = 1;
        goto cleanup;
    }

    /* The retry wrapper must be a byte-for-byte transparent fast path when
     * the first (unpermuted) ML2 attempt succeeds. */
    retry_rho = quat_ml2_retry(retried, 4, generators, d, &alg);
    if (retry_rho != 4) {
        printf("[%s] FAIL: retry rejected a successful first attempt (rho=%d)\n",
               name,
               retry_rho);
        failed = 1;
        goto cleanup;
    }
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
            if (ibz_cmp(&reduced[i][j], &retried[i][j]) != 0) {
                printf("[%s] FAIL: retry changed first-attempt output\n", name);
                failed = 1;
                goto cleanup;
            }
        }
    }

    ibz_set(&actual.denom, 1);
    for (int col = 0; col < 4; col++)
        for (int row = 0; row < 4; row++)
            ibz_copy(&actual.basis[row][col], &reduced[col][row]);

    ibz_mat_4x4_inv_with_det_as_denom(NULL, &actual_det, &actual.basis);
    if (ibz_is_zero(&actual_det)) {
        printf("[%s] FAIL: rho=4 output is not full rank\n", name);
        failed = 1;
        goto cleanup;
    }

    quat_lattice_hnf(&actual);
    if (!ibz_is_one(&actual.denom) ||
        !ibz_mat_4x4_equal(&actual.basis, &expected_hnf)) {
        printf("[%s] FAIL: ML2 output and exact HNF span different Z-lattices\n", name);
        failed = 1;
    }

cleanup:
    for (int i = 0; i < 4; i++) {
        ibz_vec_4_finalize(&retried[i]);
        ibz_vec_4_finalize(&reduced[i]);
    }
    quat_lattice_finalize(&actual);
    ibz_mat_4x4_finalize(&expected_hnf);
    ibz_mat_4x4_finalize(&independent);
    ibz_finalize(&actual_det);
    ibz_finalize(&modulus);
    quat_alg_finalize(&alg);
    return failed;
}

static void
ml2_test_weighted_dot(ibz_t *dot,
                      const ibz_vec_4_t *a,
                      const ibz_vec_4_t *b,
                      const quat_alg_t *alg)
{
    ibz_t term;
    ibz_init(&term);
    ibz_set(dot, 0);
    for (int coordinate = 0; coordinate < 4; coordinate++) {
        ibz_mul(&term, &(*a)[coordinate], &(*b)[coordinate]);
        if (coordinate >= 2)
            ibz_mul(&term, &term, &alg->p);
        ibz_add(dot, dot, &term);
    }
    ibz_finalize(&term);
}

/* Verify the exact two-vector consequences of ML2's configured eta=0.505 and
 * delta=0.995 under the reduced-norm bilinear form. */
static int
ml2_test_weighted_pair_is_lll(const ibz_vec_4_t basis[2],
                              const quat_alg_t *alg)
{
    int ok;
    ibz_t norm0, norm1, dot, abs_dot, lhs, rhs;
    ibz_init(&norm0);
    ibz_init(&norm1);
    ibz_init(&dot);
    ibz_init(&abs_dot);
    ibz_init(&lhs);
    ibz_init(&rhs);

    ml2_test_weighted_dot(&norm0, &basis[0], &basis[0], alg);
    ml2_test_weighted_dot(&norm1, &basis[1], &basis[1], alg);
    ml2_test_weighted_dot(&dot, &basis[1], &basis[0], alg);
    ibz_abs(&abs_dot, &dot);

    /* 200*|<b1,b0>| <= 101*||b0||^2. */
    ibz_set(&lhs, 200);
    ibz_mul(&lhs, &lhs, &abs_dot);
    ibz_set(&rhs, 101);
    ibz_mul(&rhs, &rhs, &norm0);
    ok = ibz_cmp(&lhs, &rhs) <= 0;

    /* ||b1||^2 >= 0.995*||b0||^2. */
    ibz_set(&lhs, 200);
    ibz_mul(&lhs, &lhs, &norm1);
    ibz_set(&rhs, 199);
    ibz_mul(&rhs, &rhs, &norm0);
    ok &= ibz_cmp(&lhs, &rhs) >= 0;

    ibz_finalize(&rhs);
    ibz_finalize(&lhs);
    ibz_finalize(&abs_dot);
    ibz_finalize(&dot);
    ibz_finalize(&norm1);
    ibz_finalize(&norm0);
    return ok;
}

static int
ml2_test_weighted_gram_and_precision(void)
{
    int failed = 0;
    int weighted_rho, euclidean_rho;
    quat_alg_t alg, large_alg;
    ibz_vec_4_t generators[2], weighted[2], euclidean[2], boundary[1], out[1];
    ibz_t determinant, tmp;

    quat_alg_init_set_ui(&alg, 101);
    quat_alg_init_set_ui(&large_alg, 3);
    for (int i = 0; i < 2; i++) {
        ibz_vec_4_init(&generators[i]);
        ibz_vec_4_init(&weighted[i]);
        ibz_vec_4_init(&euclidean[i]);
    }
    ibz_vec_4_init(&boundary[0]);
    ibz_vec_4_init(&out[0]);
    ibz_init(&determinant);
    ibz_init(&tmp);

    /* Euclidean ML2 yields (1,0,1,0),(1,0,-1,0).  With p=101 the first
     * vector is expensive in coordinate 2, so reduced-norm ML2 instead puts
     * (2,0,0,0) first and leaves (1,0,1,0) second. */
    ibz_set(&generators[0][0], 1);
    ibz_set(&generators[0][2], 1);
    ibz_set(&generators[1][0], 2);
    weighted_rho = quat_ml2(weighted, 2, generators, 2, &alg);
    euclidean_rho = quat_ml2(euclidean, 2, generators, 2, NULL);
    if (weighted_rho != 2 || euclidean_rho != 2) {
        printf("[ml2_weighted] FAIL: ranks weighted/euclidean=%d/%d\n",
               weighted_rho,
               euclidean_rho);
        failed = 1;
    } else {
        if (ml2_test_vector_arrays_identical(weighted, euclidean, 2)) {
            printf("[ml2_weighted] FAIL: alg->p did not affect reduction\n");
            failed = 1;
        }
        if (!ml2_test_weighted_pair_is_lll(weighted, &alg)) {
            printf("[ml2_weighted] FAIL: output is not reduced-norm LLL\n");
            failed = 1;
        }
        if (ml2_test_weighted_pair_is_lll(euclidean, &alg)) {
            printf("[ml2_weighted] FAIL: Euclidean fixture unexpectedly passes weighted LLL\n");
            failed = 1;
        }

        /* Projected determinant proves both outputs retain the input's
         * rank-two Z-span (index 2 in the coordinate-0/2 plane). */
        for (int which = 0; which < 2; which++) {
            const ibz_vec_4_t *basis = which == 0 ? weighted : euclidean;
            ibz_mul(&determinant, &basis[0][0], &basis[1][2]);
            ibz_mul(&tmp, &basis[0][2], &basis[1][0]);
            ibz_sub(&determinant, &determinant, &tmp);
            ibz_abs(&determinant, &determinant);
            if (ibz_cmp_int32(&determinant, 2) != 0 ||
                !ibz_is_zero(&basis[0][1]) || !ibz_is_zero(&basis[0][3]) ||
                !ibz_is_zero(&basis[1][1]) || !ibz_is_zero(&basis[1][3])) {
                printf("[ml2_weighted] FAIL: output changed the rank-two span\n");
                failed = 1;
            }
        }
    }

    /* p has 65 bits.  The same large value is safe in coordinate 0, where p
     * must not be charged, but unsafe in weighted coordinate 2. */
    ibz_set(&large_alg.p, 1);
    ibz_mul_2exp(&large_alg.p, &large_alg.p, 64);
    ibz_set(&tmp, 3);
    ibz_add(&large_alg.p, &large_alg.p, &tmp);
    ibz_set(&boundary[0][0], 1);
    ibz_mul_2exp(&boundary[0][0], &boundary[0][0],
                 (IBZ_BITS - 65) / 2 + 1);
    if (quat_ml2(out, 1, boundary, 1, &large_alg) != 1) {
        printf("[ml2_weighted_precision] FAIL: p was charged to coordinate 0\n");
        failed = 1;
    }
    ibz_copy(&boundary[0][2], &boundary[0][0]);
    ibz_set(&boundary[0][0], 0);
    if (quat_ml2(out, 1, boundary, 1, NULL) != 1 ||
        quat_ml2(out, 1, boundary, 1, &large_alg) != QUAT_ML2_ERR_PRECISION) {
        printf("[ml2_weighted_precision] FAIL: weighted p overflow was not isolated\n");
        failed = 1;
    }

    ibz_finalize(&tmp);
    ibz_finalize(&determinant);
    ibz_vec_4_finalize(&out[0]);
    ibz_vec_4_finalize(&boundary[0]);
    for (int i = 0; i < 2; i++) {
        ibz_vec_4_finalize(&euclidean[i]);
        ibz_vec_4_finalize(&weighted[i]);
        ibz_vec_4_finalize(&generators[i]);
    }
    quat_alg_finalize(&large_alg);
    quat_alg_finalize(&alg);
    return failed;
}

static int
ml2_test_span_d8(void)
{
    ibz_vec_4_t generators[8];
    ibz_mat_4x4_t target;

    ibz_mat_4x4_init(&target);
    ml2_test_set_target_hnf(&target);
    for (int i = 0; i < 8; i++) {
        ibz_vec_4_init(&generators[i]);
        ml2_test_set_generator(
            &generators[i], &target, ML2_TEST_D8_COEFFICIENTS[i]);
    }

    int failed = ml2_test_span_matches_hnf("ml2_span_d8", generators, 8, &target);

    for (int i = 0; i < 8; i++)
        ibz_vec_4_finalize(&generators[i]);
    ibz_mat_4x4_finalize(&target);
    return failed;
}

/* A zero first generator used to leave r[0][0] equal to zero.  CFA then
 * evaluated 0/0 while processing the next generator, and the resulting NaNs
 * could make ML2 report the number of nonzero generators instead of their
 * actual rank.  Exercise the minimal five-generator reproducer and all
 * production generator counts with a leading zero and further exact
 * dependencies.  The fixtures span Z^rank in the first `rank` coordinates,
 * so adjoining the remaining standard vectors must give determinant one. */
static int
ml2_test_zero_and_dependent_dimension(int d)
{
    int failed = 0;
    int expected_rank = d == 4 ? 2 : 3;
    int rho;
    quat_alg_t alg;
    ibz_t determinant;
    ibz_vec_4_t generators[ML2_TEST_MAX_GENERATORS];
    ibz_vec_4_t output[4];
    ibz_mat_4x4_t completed_basis;

    quat_alg_init_set_ui(&alg, 367);
    ibz_init(&determinant);
    ibz_mat_4x4_init(&completed_basis);
    for (int i = 0; i < d; i++)
        ibz_vec_4_init(&generators[i]);
    for (int i = 0; i < 4; i++) {
        ibz_vec_4_init(&output[i]);
        for (int coordinate = 0; coordinate < 4; coordinate++)
            ibz_set(&output[i][coordinate], -7001 - 4 * i - coordinate);
    }

    /* [0,e0,e0,e1] at d=4, and the same prefix followed by e2 and
     * dependent combinations of e0,e1,e2 at every larger fixture. */
    ibz_set(&generators[1][0], 1);
    ibz_set(&generators[2][0], 1);
    ibz_set(&generators[3][1], 1);
    if (d > 4)
        ibz_set(&generators[4][2], 1);
    for (int i = 5; i < d; i++) {
        ibz_set(&generators[i][(i - 5) % expected_rank], 1);
        ibz_set(&generators[i][(i - 4) % expected_rank],
                (i & 1) == 0 ? 1 : -1);
    }

    rho = quat_ml2(output, 4, generators, d, &alg);
    if (rho != expected_rank) {
        printf("[ml2_zero_dependent_d%d] FAIL: expected rho=%d, got %d\n",
               d,
               expected_rank,
               rho);
        failed = 1;
        goto all_zero;
    }

    ibz_mat_4x4_zero(&completed_basis);
    for (int col = 0; col < expected_rank; col++) {
        for (int row = 0; row < 4; row++)
            ibz_copy(&completed_basis[row][col], &output[col][row]);
        for (int row = expected_rank; row < 4; row++) {
            if (!ibz_is_zero(&output[col][row])) {
                printf("[ml2_zero_dependent_d%d] FAIL: output left the input span\n",
                       d);
                failed = 1;
            }
        }
    }
    for (int col = expected_rank; col < 4; col++)
        ibz_set(&completed_basis[col][col], 1);
    ibz_mat_4x4_inv_with_det_as_denom(NULL, &determinant, &completed_basis);
    ibz_abs(&determinant, &determinant);
    if (!ibz_is_one(&determinant)) {
        printf("[ml2_zero_dependent_d%d] FAIL: output changed the exact span\n",
               d);
        failed = 1;
    }
    for (int i = expected_rank; i < 4; i++) {
        for (int coordinate = 0; coordinate < 4; coordinate++) {
            if (ibz_cmp_int32(&output[i][coordinate],
                              -7001 - 4 * i - coordinate) != 0) {
                printf("[ml2_zero_dependent_d%d] FAIL: wrote past rho\n", d);
                failed = 1;
                goto all_zero;
            }
        }
    }

all_zero:
    for (int i = 0; i < d; i++)
        for (int coordinate = 0; coordinate < 4; coordinate++)
            ibz_set(&generators[i][coordinate], 0);
    for (int i = 0; i < 4; i++)
        for (int coordinate = 0; coordinate < 4; coordinate++)
            ibz_set(&output[i][coordinate], 8001 + 4 * i + coordinate);
    rho = quat_ml2(output, 4, generators, d, &alg);
    if (rho != 0) {
        printf("[ml2_all_zero_d%d] FAIL: expected rho=0, got %d\n", d, rho);
        failed = 1;
    }
    for (int i = 0; i < 4; i++) {
        for (int coordinate = 0; coordinate < 4; coordinate++) {
            if (ibz_cmp_int32(&output[i][coordinate],
                              8001 + 4 * i + coordinate) != 0) {
                printf("[ml2_all_zero_d%d] FAIL: rank-zero call modified output\n",
                       d);
                failed = 1;
                goto cleanup;
            }
        }
    }

cleanup:
    for (int i = 0; i < 4; i++)
        ibz_vec_4_finalize(&output[i]);
    for (int i = 0; i < d; i++)
        ibz_vec_4_finalize(&generators[i]);
    ibz_mat_4x4_finalize(&completed_basis);
    ibz_finalize(&determinant);
    quat_alg_finalize(&alg);
    return failed;
}

static int
ml2_test_span_d16_high_dynamic(void)
{
    static const int32_t coefficients[16][4] = {
        { 1, 0, 0, 0 },
        { 0, 1, 0, 0 },
        { 0, 0, 1, 0 },
        { 0, 0, 0, 1 },
        { 1, 1, 0, 0 },
        { 0, 1, 1, 0 },
        { 0, 0, 1, 1 },
        { 1, 0, 1, -1 },
        { 2, 2, 0, 0 },
        { 0, -1, -1, 0 },
        { 1, 2, 1, 0 },
        { 1, 1, 0, 0 },
        { -3, 0, 2, 1 },
        { 0, 5, -2, 3 },
        { 7, -4, 1, -6 },
        { -2, 3, 0, 5 },
    };
    ibz_vec_4_t generators[ML2_TEST_MAX_GENERATORS];
    ibz_mat_4x4_t target;
    ibz_t scale, low_part;

    ibz_mat_4x4_init(&target);
    ibz_init(&scale);
    ibz_init(&low_part);
    ml2_test_set_target_hnf(&target);
    for (int i = 0; i < ML2_TEST_MAX_GENERATORS; i++) {
        ibz_vec_4_init(&generators[i]);
        ml2_test_set_generator(&generators[i], &target, coefficients[i]);
    }

    /* scale = 2^80 + 2^40 + 2.  The low part is below the DPE ulp at this
     * magnitude, while the exact integer updates must still preserve it.
     * Also scale is not divisible by 3; together with the determinant -3 of
     * coefficient rows 4..7 this proves that the coefficient lattice is Z^4.
     * The oracle determinant remains about 333 bits, safely within lvl1. */
    ibz_set(&scale, 1);
    ibz_mul_2exp(&scale, &scale, 80);
    ibz_set(&low_part, 1);
    ibz_mul_2exp(&low_part, &low_part, 40);
    ibz_add(&scale, &scale, &low_part);
    ibz_set(&low_part, 2);
    ibz_add(&scale, &scale, &low_part);
    for (int i = 0; i < 4; i++)
        for (int row = 0; row < 4; row++)
            ibz_mul(&generators[i][row], &generators[i][row], &scale);

    int failed = ml2_test_span_matches_hnf(
        "ml2_span_d16_2pow80", generators, ML2_TEST_MAX_GENERATORS, &target);

    for (int i = 0; i < ML2_TEST_MAX_GENERATORS; i++)
        ibz_vec_4_finalize(&generators[i]);
    ibz_finalize(&low_part);
    ibz_finalize(&scale);
    ibz_mat_4x4_finalize(&target);
    return failed;
}

static int
ml2_test_vector_arrays_identical(const ibz_vec_4_t *a,
                                 const ibz_vec_4_t *b,
                                 int count)
{
    for (int i = 0; i < count; i++)
        for (int j = 0; j < 4; j++)
            if (ibz_cmp(&a[i][j], &b[i][j]) != 0)
                return 0;
    return 1;
}

static uint64_t
ml2_test_hash_generators(const ibz_vec_4_t *input, int d)
{
    uint64_t hash = UINT64_C(1469598103934665603);
    for (int i = 0; i < d; i++) {
        for (int j = 0; j < 4; j++) {
            for (int limb = 0; limb < IBZ_LIMBS; limb++) {
                hash ^= input[i][j][limb];
                hash *= UINT64_C(1099511628211);
            }
        }
    }
    return hash;
}

typedef enum {
    ML2_RETRY_TEST_RECOVER_ON_SECOND,
    ML2_RETRY_TEST_ALWAYS_FAIL,
} ml2_retry_test_mode_t;

typedef struct {
    ml2_retry_test_mode_t mode;
    int calls;
    uint64_t input_hashes[QUAT_ML2_RETRY_MAX_ATTEMPTS];
} ml2_retry_test_state_t;

static ml2_retry_test_state_t ml2_retry_test_state;

static void
ml2_retry_test_reset(ml2_retry_test_mode_t mode)
{
    ml2_retry_test_state.mode = mode;
    ml2_retry_test_state.calls = 0;
    for (int i = 0; i < QUAT_ML2_RETRY_MAX_ATTEMPTS; i++)
        ml2_retry_test_state.input_hashes[i] = 0;
}

static int
ml2_retry_test_reducer(ibz_vec_4_t *output,
                       int out_capacity,
                       const ibz_vec_4_t *input,
                       int d,
                       const quat_alg_t *alg)
{
    int attempt = ml2_retry_test_state.calls++;
    if (attempt < QUAT_ML2_RETRY_MAX_ATTEMPTS)
        ml2_retry_test_state.input_hashes[attempt] =
            ml2_test_hash_generators(input, d);

    /* Deliberately dirty the per-attempt buffer.  The retry driver must not
     * expose this data unless this exact attempt returns rank four. */
    for (int i = 0; i < out_capacity; i++)
        for (int j = 0; j < 4; j++)
            ibz_set(&output[i][j], 301 + 17 * attempt + 4 * i + j);

    if (ml2_retry_test_state.mode == ML2_RETRY_TEST_RECOVER_ON_SECOND &&
        attempt == 1)
        return quat_ml2(output, out_capacity, input, d, alg);

    /* Check that the wrapper returns the first failure code, not the last. */
    return attempt == 0 ? 3 : -1;
}

#if defined(SQISIGN_ML2_PROFILE)
typedef enum {
    ML2_PROFILE_TEST_RECOVER,
    ML2_PROFILE_TEST_EXHAUST,
} ml2_profile_test_mode_t;

static struct {
    ml2_profile_test_mode_t mode;
    int calls;
    uint64_t hashes[QUAT_ML2_RETRY_MAX_ATTEMPTS];
} ml2_profile_test_reducer_state;

static int
ml2_profile_test_reducer(ibz_vec_4_t *output,
                         int out_capacity,
                         const ibz_vec_4_t *input,
                         int d,
                         const quat_alg_t *alg)
{
    int attempt = ml2_profile_test_reducer_state.calls++;
    if (attempt < QUAT_ML2_RETRY_MAX_ATTEMPTS)
        ml2_profile_test_reducer_state.hashes[attempt] =
            ml2_test_hash_generators(input, d);
    if (ml2_profile_test_reducer_state.mode == ML2_PROFILE_TEST_RECOVER &&
        attempt == 1)
        return quat_ml2(output, out_capacity, input, d, alg);
    return -1;
}

static void
ml2_profile_test_reducer_reset(ml2_profile_test_mode_t mode)
{
    ml2_profile_test_reducer_state.mode = mode;
    ml2_profile_test_reducer_state.calls = 0;
    for (int i = 0; i < QUAT_ML2_RETRY_MAX_ATTEMPTS; i++)
        ml2_profile_test_reducer_state.hashes[i] = 0;
}

static int
ml2_profile_dimension_equals(const quat_ml2_profile_dimension_t *profile,
                             uint64_t inputs,
                             uint64_t precision_rejected,
                             uint64_t first_failures,
                             uint64_t recovered_1,
                             uint64_t recovered_2,
                             uint64_t recovered_3,
                             uint64_t exhausted,
                             uint64_t underlying_attempts)
{
    return profile->inputs == inputs &&
           profile->precision_rejected == precision_rejected &&
           profile->first_attempt_failures == first_failures &&
           profile->recovered[0] == recovered_1 &&
           profile->recovered[1] == recovered_2 &&
           profile->recovered[2] == recovered_3 &&
           profile->exhausted == exhausted &&
           profile->underlying_attempts == underlying_attempts;
}

#define ML2_PROFILE_THREAD_COUNT 4
#define ML2_PROFILE_THREAD_ITERATIONS 25

typedef struct {
    const quat_alg_t *alg;
    int failed;
} ml2_profile_thread_argument_t;

static void *
ml2_profile_thread_worker(void *opaque)
{
    ml2_profile_thread_argument_t *argument = opaque;
    ibz_vec_4_t generators[4];
    ibz_mat_4x4_t basis;
    int rank;

    ibz_mat_4x4_init(&basis);
    for (int i = 0; i < 4; i++) {
        ibz_vec_4_init(&generators[i]);
        ibz_set(&generators[i][i], 1);
    }

    argument->failed = 0;
    for (int iteration = 0; iteration < ML2_PROFILE_THREAD_ITERATIONS;
         iteration++) {
        quat_mlll(&basis, &rank, generators, 4, argument->alg);
        if (rank != 4) {
            argument->failed = 1;
            break;
        }
    }

    for (int i = 0; i < 4; i++)
        ibz_vec_4_finalize(&generators[i]);
    ibz_mat_4x4_finalize(&basis);
    return NULL;
}

static int
ml2_test_profile_accounting(void)
{
    int failed = 0;
    int rho;
    int rank;
    quat_alg_t alg;
    ibz_vec_4_t generators[4], output[4];
    ibz_mat_4x4_t basis;
    quat_ml2_profile_t profile;
    pthread_t threads[ML2_PROFILE_THREAD_COUNT];
    ml2_profile_thread_argument_t arguments[ML2_PROFILE_THREAD_COUNT];

    quat_alg_init_set_ui(&alg, 101);
    ibz_mat_4x4_init(&basis);
    for (int i = 0; i < 4; i++) {
        ibz_vec_4_init(&generators[i]);
        ibz_vec_4_init(&output[i]);
        ibz_set(&generators[i][i], 1);
    }

    /* The actual quat_mlll callsite must count one logical input and its one
     * successful attempt, rather than bypassing the retry profiler. */
    quat_ml2_profile_reset();
    quat_mlll(&basis, &rank, generators, 4, &alg);
    quat_ml2_profile_get(&profile);
    if (rank != 4 ||
        !ml2_profile_dimension_equals(
            &profile.d4, 1, 0, 0, 0, 0, 0, 0, 1)) {
        printf("[ml2_profile_mlll] FAIL: first-success accounting is incorrect\n");
        failed = 1;
    }

    /* A failed attempt 0 followed by recovery must execute exactly the
     * rotated ordering once and record recovered_1. */
    quat_ml2_profile_reset();
    ml2_profile_test_reducer_reset(ML2_PROFILE_TEST_RECOVER);
    rho = quat_ml2_mlll_with_reducer(
        output, 4, generators, 4, &alg, ml2_profile_test_reducer);
    quat_ml2_profile_get(&profile);
    if (rho != 4 || ml2_profile_test_reducer_state.calls != 2 ||
        ml2_profile_test_reducer_state.hashes[0] ==
            ml2_profile_test_reducer_state.hashes[1] ||
        !ml2_profile_dimension_equals(
            &profile.d4, 1, 0, 1, 1, 0, 0, 0, 2)) {
        printf("[ml2_profile_mlll] FAIL: recovery accounting/order is incorrect\n");
        failed = 1;
    }

    quat_ml2_profile_reset();
    ml2_profile_test_reducer_reset(ML2_PROFILE_TEST_EXHAUST);
    rho = quat_ml2_mlll_with_reducer(
        output, 4, generators, 4, &alg, ml2_profile_test_reducer);
    quat_ml2_profile_get(&profile);
    if (rho != -1 ||
        ml2_profile_test_reducer_state.calls != QUAT_ML2_RETRY_MAX_ATTEMPTS ||
        !ml2_profile_dimension_equals(
            &profile.d4, 1, 0, 1, 0, 0, 0, 1, 4)) {
        printf("[ml2_profile_mlll] FAIL: exhausted accounting is incorrect\n");
        failed = 1;
    }

    /* Precision rejection is a logical input but executes no reducer. */
    ibz_set(&generators[0][0], 1);
    ibz_mul_2exp(&generators[0][0], &generators[0][0], IBZ_BITS / 2);
    quat_ml2_profile_reset();
    ml2_profile_test_reducer_reset(ML2_PROFILE_TEST_EXHAUST);
    rho = quat_ml2_mlll_with_reducer(
        output, 4, generators, 4, &alg, ml2_profile_test_reducer);
    quat_ml2_profile_get(&profile);
    if (rho != QUAT_ML2_ERR_PRECISION ||
        ml2_profile_test_reducer_state.calls != 0 ||
        !ml2_profile_dimension_equals(
            &profile.d4, 1, 1, 0, 0, 0, 0, 0, 0)) {
        printf("[ml2_profile_mlll] FAIL: precision accounting is incorrect\n");
        failed = 1;
    }
    ibz_set(&generators[0][0], 1);

    /* Concurrent first-success calls must not lose atomic increments. */
    quat_ml2_profile_reset();
    int created = 0;
    for (int i = 0; i < ML2_PROFILE_THREAD_COUNT; i++) {
        arguments[i].alg = &alg;
        arguments[i].failed = 0;
        if (pthread_create(
                &threads[i], NULL, ml2_profile_thread_worker, &arguments[i]) != 0) {
            failed = 1;
            break;
        }
        created++;
    }
    for (int i = 0; i < created; i++) {
        if (pthread_join(threads[i], NULL) != 0 || arguments[i].failed)
            failed = 1;
    }
    quat_ml2_profile_get(&profile);
    uint64_t expected =
        (uint64_t)created * (uint64_t)ML2_PROFILE_THREAD_ITERATIONS;
    if (created != ML2_PROFILE_THREAD_COUNT ||
        !ml2_profile_dimension_equals(
            &profile.d4, expected, 0, 0, 0, 0, 0, 0, expected)) {
        printf("[ml2_profile_threads] FAIL: concurrent counters are incorrect\n");
        failed = 1;
    }

    for (int i = 0; i < 4; i++) {
        ibz_vec_4_finalize(&output[i]);
        ibz_vec_4_finalize(&generators[i]);
    }
    ibz_mat_4x4_finalize(&basis);
    quat_alg_finalize(&alg);
    return failed;
}
#endif

static int
ml2_test_output_matches_hnf(const ibz_vec_4_t output[4],
                            const ibz_mat_4x4_t *expected_hnf)
{
    int matches;
    ibz_t det;
    quat_lattice_t lattice;
    ibz_init(&det);
    quat_lattice_init(&lattice);
    ibz_set(&lattice.denom, 1);
    for (int col = 0; col < 4; col++)
        for (int row = 0; row < 4; row++)
            ibz_copy(&lattice.basis[row][col], &output[col][row]);

    ibz_mat_4x4_inv_with_det_as_denom(NULL, &det, &lattice.basis);
    if (ibz_is_zero(&det)) {
        matches = 0;
    } else {
        quat_lattice_hnf(&lattice);
        matches = ibz_is_one(&lattice.denom) &&
                  ibz_mat_4x4_equal(&lattice.basis, expected_hnf);
    }

    quat_lattice_finalize(&lattice);
    ibz_finalize(&det);
    return matches;
}

static int
ml2_test_retry_recovery_and_nonpublication(void)
{
    int failed = 0;
    int rho;
    int first_calls;
    uint64_t first_hashes[QUAT_ML2_RETRY_MAX_ATTEMPTS];
    ibz_vec_4_t generators[8];
    ibz_vec_4_t recovered1[4], recovered2[4], unchanged[4], before[4];
    ibz_mat_4x4_t target;

    ibz_mat_4x4_init(&target);
    ml2_test_set_target_hnf(&target);
    for (int i = 0; i < 8; i++) {
        ibz_vec_4_init(&generators[i]);
        ml2_test_set_generator(
            &generators[i], &target, ML2_TEST_D8_COEFFICIENTS[i]);
    }
    for (int i = 0; i < 4; i++) {
        ibz_vec_4_init(&recovered1[i]);
        ibz_vec_4_init(&recovered2[i]);
        ibz_vec_4_init(&unchanged[i]);
        ibz_vec_4_init(&before[i]);
    }

    ml2_retry_test_reset(ML2_RETRY_TEST_RECOVER_ON_SECOND);
    rho = quat_ml2_retry_with_reducer(
        recovered1, 4, generators, 8, NULL, ml2_retry_test_reducer);
    first_calls = ml2_retry_test_state.calls;
    for (int i = 0; i < 4; i++)
        first_hashes[i] = ml2_retry_test_state.input_hashes[i];
    if (rho != 4 || first_calls != 2) {
        printf("[ml2_retry_recover] FAIL: rho=%d calls=%d, expected 4/2\n",
               rho,
               first_calls);
        failed = 1;
    } else if (first_hashes[0] == first_hashes[1]) {
        printf("[ml2_retry_recover] FAIL: retry did not permute its input\n");
        failed = 1;
    } else if (!ml2_test_output_matches_hnf(recovered1, &target)) {
        printf("[ml2_retry_recover] FAIL: recovered output has the wrong span\n");
        failed = 1;
    }

    /* Running the same input twice must use the same permutation schedule and
     * return the same recovered integer basis. */
    ml2_retry_test_reset(ML2_RETRY_TEST_RECOVER_ON_SECOND);
    rho = quat_ml2_retry_with_reducer(
        recovered2, 4, generators, 8, NULL, ml2_retry_test_reducer);
    if (rho != 4 || ml2_retry_test_state.calls != first_calls ||
        !ml2_test_vector_arrays_identical(recovered1, recovered2, 4)) {
        printf("[ml2_retry_reproducible] FAIL: retry result is not deterministic\n");
        failed = 1;
    }
    for (int i = 0; i < first_calls; i++) {
        if (ml2_retry_test_state.input_hashes[i] != first_hashes[i]) {
            printf("[ml2_retry_reproducible] FAIL: permutation trace changed\n");
            failed = 1;
            break;
        }
    }

    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
            ibz_set(&unchanged[i][j], -901 - 4 * i - j);
            ibz_copy(&before[i][j], &unchanged[i][j]);
        }
    }
    ml2_retry_test_reset(ML2_RETRY_TEST_ALWAYS_FAIL);
    rho = quat_ml2_retry_with_reducer(
        unchanged, 4, generators, 8, NULL, ml2_retry_test_reducer);
    if (rho != 3 ||
        ml2_retry_test_state.calls != QUAT_ML2_RETRY_MAX_ATTEMPTS) {
        printf("[ml2_retry_all_fail] FAIL: rho=%d calls=%d, expected 3/%d\n",
               rho,
               ml2_retry_test_state.calls,
               QUAT_ML2_RETRY_MAX_ATTEMPTS);
        failed = 1;
    }
    if (!ml2_test_vector_arrays_identical(unchanged, before, 4)) {
        printf("[ml2_retry_all_fail] FAIL: failed attempts modified output\n");
        failed = 1;
    }

    /* The retry API only publishes a complete four-vector basis.  A smaller
     * destination must be rejected before invoking the reducer. */
    ml2_retry_test_reset(ML2_RETRY_TEST_ALWAYS_FAIL);
    rho = quat_ml2_retry_with_reducer(
        unchanged, 3, generators, 8, NULL, ml2_retry_test_reducer);
    if (rho != -1 || ml2_retry_test_state.calls != 0) {
        printf("[ml2_retry_capacity] FAIL: rho=%d calls=%d, expected -1/0\n",
               rho,
               ml2_retry_test_state.calls);
        failed = 1;
    }
    if (!ml2_test_vector_arrays_identical(unchanged, before, 4)) {
        printf("[ml2_retry_capacity] FAIL: invalid capacity modified output\n");
        failed = 1;
    }

    /* A generator whose conservative squared norm cannot fit in the active
     * signed width must be rejected before either ML2 or its permutations are
     * called.  Reordering cannot make this input safe. */
    ibz_set(&generators[0][0], 1);
    ibz_mul_2exp(&generators[0][0], &generators[0][0], IBZ_BITS / 2);
    ml2_retry_test_reset(ML2_RETRY_TEST_ALWAYS_FAIL);
    rho = quat_ml2_retry_with_reducer(
        unchanged, 4, generators, 8, NULL, ml2_retry_test_reducer);
    if (rho != QUAT_ML2_ERR_PRECISION || ml2_retry_test_state.calls != 0) {
        printf("[ml2_retry_precision] FAIL: rho=%d calls=%d, expected %d/0\n",
               rho,
               ml2_retry_test_state.calls,
               QUAT_ML2_ERR_PRECISION);
        failed = 1;
    }
    if (!ml2_test_vector_arrays_identical(unchanged, before, 4)) {
        printf("[ml2_retry_precision] FAIL: unsafe input modified output\n");
        failed = 1;
    }

    for (int i = 0; i < 4; i++) {
        ibz_vec_4_finalize(&before[i]);
        ibz_vec_4_finalize(&unchanged[i]);
        ibz_vec_4_finalize(&recovered2[i]);
        ibz_vec_4_finalize(&recovered1[i]);
    }
    for (int i = 0; i < 8; i++)
        ibz_vec_4_finalize(&generators[i]);
    ibz_mat_4x4_finalize(&target);
    return failed;
}

static void
ml2_test_set_scalar_lattice(quat_lattice_t *lat, int32_t basis_scalar, int32_t denom)
{
    ibz_mat_4x4_zero(&lat->basis);
    for (int i = 0; i < 4; i++)
        ibz_set(&lat->basis[i][i], basis_scalar);
    ibz_set(&lat->denom, denom);
}

static void
ml2_test_copy_lattice(quat_lattice_t *copy, const quat_lattice_t *source)
{
    ibz_mat_4x4_copy(&copy->basis, &source->basis);
    ibz_copy(&copy->denom, &source->denom);
}

static int
ml2_test_lattice_identical(const quat_lattice_t *a, const quat_lattice_t *b)
{
    return ibz_cmp(&a->denom, &b->denom) == 0 &&
           ibz_mat_4x4_equal(&a->basis, &b->basis);
}

static int
ml2_test_multiplication_alias_and_nonpublication(void)
{
    int failed = 0;
    quat_alg_t alg;
    quat_lattice_t lat1, lat2, expected, result, alias_left, alias_right, before;

    quat_alg_init_set_ui(&alg, 3);
    quat_lattice_init(&lat1);
    quat_lattice_init(&lat2);
    quat_lattice_init(&expected);
    quat_lattice_init(&result);
    quat_lattice_init(&alias_left);
    quat_lattice_init(&alias_right);
    quat_lattice_init(&before);

    ml2_test_set_scalar_lattice(&lat1, 2, 1);
    ml2_test_set_scalar_lattice(&lat2, 3, 1);
    ml2_test_set_scalar_lattice(&expected, 6, 1);

    /* Replace the 2*Z^4 basis by a deliberately long unimodular basis of
     * the same lattice. CompactIdealMultiplication must L2-reduce its inputs
     * before it forms the sixteen products. */
    ibz_set(&lat1.basis[0][1], 14);
    ibz_set(&lat1.basis[0][2], -10);
    ibz_set(&lat1.basis[1][2], 6);
    ibz_set(&lat1.basis[0][3], 22);
    ibz_set(&lat1.basis[1][3], -8);
    ibz_set(&lat1.basis[2][3], 12);

    ml2_test_set_scalar_lattice(&result, 17, 19);
    if (!quat_lattice_mul_mlll(&result, &lat1, &lat2, &alg) ||
        !quat_lattice_equal(&result, &expected)) {
        printf("[mlll_mul] FAIL: scalar product lattice is incorrect\n");
        failed = 1;
    }

    ml2_test_copy_lattice(&alias_left, &lat1);
    if (!quat_lattice_mul_mlll(&alias_left, &alias_left, &lat2, &alg) ||
        !quat_lattice_equal(&alias_left, &expected)) {
        printf("[mlll_mul_alias] FAIL: res == lat1 is not alias-safe\n");
        failed = 1;
    }

    ml2_test_copy_lattice(&alias_right, &lat2);
    if (!quat_lattice_mul_mlll(&alias_right, &lat1, &alias_right, &alg) ||
        !quat_lattice_equal(&alias_right, &expected)) {
        printf("[mlll_mul_alias] FAIL: res == lat2 is not alias-safe\n");
        failed = 1;
    }

    /* Force the product-coordinate preflight to reject before arithmetic;
     * the destination must remain byte-for-byte unchanged. */
    ml2_test_set_scalar_lattice(&lat1, 1, 1);
    ibz_set(&lat1.basis[0][0], 1);
    ibz_mul_2exp(&lat1.basis[0][0], &lat1.basis[0][0], IBZ_BITS - 3);
    ml2_test_set_scalar_lattice(&result, 23, 29);
    ml2_test_copy_lattice(&before, &result);
    if (quat_lattice_mul_mlll(&result, &lat1, &lat2, &alg) != 0 ||
        !ml2_test_lattice_identical(&result, &before)) {
        printf("[mlll_mul_failure] FAIL: precision rejection modified output\n");
        failed = 1;
    }

    quat_lattice_finalize(&before);
    quat_lattice_finalize(&alias_right);
    quat_lattice_finalize(&alias_left);
    quat_lattice_finalize(&result);
    quat_lattice_finalize(&expected);
    quat_lattice_finalize(&lat2);
    quat_lattice_finalize(&lat1);
    quat_alg_finalize(&alg);
    return failed;
}

static int
ml2_test_fake_abort(ibz_vec_4_t *output,
                    int out_capacity,
                    const ibz_vec_4_t *input,
                    int d,
                    const quat_alg_t *alg)
{
    (void)input;
    (void)d;
    (void)alg;
    for (int i = 0; i < out_capacity; i++)
        for (int j = 0; j < 4; j++)
            ibz_set(&output[i][j], 41 + 4 * i + j);
    return -1;
}

static int
ml2_test_fake_rank3(ibz_vec_4_t *output,
                    int out_capacity,
                    const ibz_vec_4_t *input,
                    int d,
                    const quat_alg_t *alg)
{
    (void)input;
    (void)d;
    (void)alg;
    for (int i = 0; i < out_capacity; i++)
        for (int j = 0; j < 4; j++)
            ibz_set(&output[i][j], -73 - 4 * i - j);
    return 3;
}

static int
ml2_test_fake_rank5(ibz_vec_4_t *output,
                    int out_capacity,
                    const ibz_vec_4_t *input,
                    int d,
                    const quat_alg_t *alg)
{
    (void)input;
    (void)d;
    (void)alg;
    for (int i = 0; i < out_capacity; i++)
        for (int j = 0; j < 4; j++)
            ibz_set(&output[i][j], 101 + 4 * i + j);
    return 5;
}

static int
ml2_test_addition_and_failure_nonpublication(void)
{
    int failed = 0;
    quat_alg_t alg;
    quat_lattice_t lat1, lat2, expected, result, before;

    quat_alg_init_set_ui(&alg, 3);
    quat_lattice_init(&lat1);
    quat_lattice_init(&lat2);
    quat_lattice_init(&expected);
    quat_lattice_init(&result);
    quat_lattice_init(&before);

    /* (4 Z^4)/2 = 2 Z^4 and (9 Z^4)/3 = 3 Z^4; their sum is Z^4. */
    ml2_test_set_scalar_lattice(&lat1, 4, 2);
    ml2_test_set_scalar_lattice(&lat2, 9, 3);
    ml2_test_set_scalar_lattice(&expected, 1, 1);

    ml2_test_set_scalar_lattice(&result, 13, 29);
    if (!quat_lattice_add_mlll_with_reducer(
            &result, &lat1, &lat2, &alg, quat_ml2)) {
        printf("[ml2_add] FAIL: valid rank-4 reduction was rejected\n");
        failed = 1;
    } else if (!quat_lattice_equal(&result, &expected)) {
        printf("[ml2_add] FAIL: 2 Z^4 + 3 Z^4 != Z^4\n");
        failed = 1;
    }

    /* A failed or incomplete reducer must not publish scratch output or a
     * denominator into the caller's destination. */
    ml2_test_set_scalar_lattice(&result, 13, 29);
    ml2_test_copy_lattice(&before, &result);
    if (quat_lattice_add_mlll_with_reducer(
            &result, &lat1, &lat2, &alg, ml2_test_fake_abort) != 0) {
        printf("[ml2_add_abort] FAIL: rho=-1 was accepted\n");
        failed = 1;
    }
    if (!ml2_test_lattice_identical(&result, &before)) {
        printf("[ml2_add_abort] FAIL: rho=-1 modified the destination\n");
        failed = 1;
    }

    if (quat_lattice_add_mlll_with_reducer(
            &result, &lat1, &lat2, &alg, ml2_test_fake_rank3) != 0) {
        printf("[ml2_add_rank3] FAIL: rho=3 was accepted\n");
        failed = 1;
    }
    if (!ml2_test_lattice_identical(&result, &before)) {
        printf("[ml2_add_rank3] FAIL: rho=3 modified the destination\n");
        failed = 1;
    }

    if (quat_lattice_add_mlll_with_reducer(
            &result, &lat1, &lat2, &alg, ml2_test_fake_rank5) != 0) {
        printf("[ml2_add_rank5] FAIL: rho=5 was accepted\n");
        failed = 1;
    }
    if (!ml2_test_lattice_identical(&result, &before)) {
        printf("[ml2_add_rank5] FAIL: rho=5 modified the destination\n");
        failed = 1;
    }

    quat_lattice_finalize(&before);
    quat_lattice_finalize(&result);
    quat_lattice_finalize(&expected);
    quat_lattice_finalize(&lat2);
    quat_lattice_finalize(&lat1);
    quat_alg_finalize(&alg);
    return failed;
}

/* ---------- Opt-in synthetic failure-rate measurement ----------
 *
 * This is not part of CTest.  It is selected explicitly by the quaternion
 * runner's --ml2-stress=N mode so large samples do not slow correctness CI.
 * The local PRNG and fixed seed make every row reproducible without consuming
 * the application's randombytes transcript. */

static uint64_t ml2_stress_prng_state;

static uint64_t
ml2_stress_next_u64(void)
{
    uint64_t x = ml2_stress_prng_state;
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    ml2_stress_prng_state = x;
    return x * UINT64_C(2685821657736338717);
}

static unsigned
ml2_stress_coefficient_bits(void)
{
    static const unsigned bands[] = {
        12,
        55,
        80,
        IBZ_BITS / 4,
        IBZ_BITS / 2 - 16,
    };
    uint64_t random = ml2_stress_next_u64();
    return bands[random % (sizeof(bands) / sizeof(bands[0]))] +
           (unsigned)((random >> 8) % 8);
}

static void
ml2_stress_set_signed_coefficient(ibz_t *coefficient, unsigned bits)
{
    ibz_t top;
    uint64_t low = ml2_stress_next_u64() | UINT64_C(1);
    ibz_init(&top);
    ibz_set_u64(coefficient, low);

    if (bits < 64) {
        uint64_t mask = (UINT64_C(1) << bits) - 1;
        low &= mask;
        low |= UINT64_C(1) << (bits - 1);
        ibz_set_u64(coefficient, low);
    } else {
        ibz_set(&top, 1);
        ibz_mul_2exp(&top, &top, bits - 1);
        ibz_add(coefficient, coefficient, &top);
    }

    if (ml2_stress_next_u64() & 1)
        ibz_neg(coefficient, coefficient);
    ibz_finalize(&top);
}

static void
ml2_test_set_generator_ibz(ibz_vec_4_t *generator,
                           const ibz_mat_4x4_t *target,
                           const ibz_t coefficients[4])
{
    ibz_t term;
    ibz_init(&term);
    for (int row = 0; row < 4; row++) {
        ibz_set(&(*generator)[row], 0);
        for (int col = 0; col < 4; col++) {
            ibz_mul(&term, &(*target)[row][col], &coefficients[col]);
            ibz_add(&(*generator)[row], &(*generator)[row], &term);
        }
    }
    ibz_finalize(&term);
}

static void
ml2_stress_build_generators(ibz_vec_4_t *generators,
                            int d,
                            const ibz_mat_4x4_t *target)
{
    ibz_t coefficients[4];
    for (int i = 0; i < 4; i++)
        ibz_init(&coefficients[i]);

    /* Four scaled target columns guarantee full rank.  Scales are sampled
     * across and beyond the 53-bit DPE precision boundary. */
    for (int vector = 0; vector < 4; vector++) {
        for (int i = 0; i < 4; i++)
            ibz_set(&coefficients[i], 0);
        ml2_stress_set_signed_coefficient(
            &coefficients[vector], ml2_stress_coefficient_bits());
        ml2_test_set_generator_ibz(&generators[vector], target, coefficients);
    }

    /* Remaining vectors are exact, redundant Z-combinations with one large
     * coefficient and three smaller signed coefficients. */
    for (int vector = 4; vector < d; vector++) {
        int dominant = (int)(ml2_stress_next_u64() & 3);
        for (int i = 0; i < 4; i++) {
            unsigned bits = (i == dominant)
                                ? ml2_stress_coefficient_bits()
                                : 8 + (unsigned)(ml2_stress_next_u64() % 24);
            ml2_stress_set_signed_coefficient(&coefficients[i], bits);
        }
        ml2_test_set_generator_ibz(&generators[vector], target, coefficients);
    }

    /* Deterministic Fisher-Yates shuffle exercises order sensitivity while
     * preserving the guaranteed full-rank generator set. */
    for (int i = d - 1; i > 0; i--) {
        int j = (int)(ml2_stress_next_u64() % (uint64_t)(i + 1));
        for (int coordinate = 0; coordinate < 4; coordinate++)
            ibz_swap(&generators[i][coordinate], &generators[j][coordinate]);
    }

    for (int i = 0; i < 4; i++)
        ibz_finalize(&coefficients[i]);
}

static uint64_t
ml2_stress_mod_pow(uint64_t base, uint64_t exponent, uint64_t modulus)
{
    uint64_t result = 1;
    while (exponent != 0) {
        if (exponent & 1)
            result = (result * base) % modulus;
        base = (base * base) % modulus;
        exponent >>= 1;
    }
    return result;
}

static int
ml2_stress_rank_mod_prime(const ibz_vec_4_t output[4], uint64_t prime)
{
    uint64_t matrix[4][4];
    int rank = 0;
    for (int row = 0; row < 4; row++)
        for (int column = 0; column < 4; column++)
            matrix[row][column] = ibz_mod_ui(&output[column][row], prime);

    for (int column = 0; column < 4 && rank < 4; column++) {
        int pivot = rank;
        while (pivot < 4 && matrix[pivot][column] == 0)
            pivot++;
        if (pivot == 4)
            continue;
        if (pivot != rank) {
            for (int j = column; j < 4; j++) {
                uint64_t tmp = matrix[rank][j];
                matrix[rank][j] = matrix[pivot][j];
                matrix[pivot][j] = tmp;
            }
        }
        uint64_t inverse = ml2_stress_mod_pow(
            matrix[rank][column], prime - 2, prime);
        for (int j = column; j < 4; j++)
            matrix[rank][j] = (matrix[rank][j] * inverse) % prime;
        for (int row = 0; row < 4; row++) {
            if (row == rank)
                continue;
            uint64_t factor = matrix[row][column];
            for (int j = column; j < 4; j++) {
                uint64_t product = (factor * matrix[rank][j]) % prime;
                matrix[row][j] = (matrix[row][j] + prime - product) % prime;
            }
        }
        rank++;
    }
    return rank;
}

static int
ml2_stress_reported_basis_is_full_rank(const ibz_vec_4_t output[4])
{
    static const uint64_t primes[] = {
        UINT64_C(2147483647), UINT64_C(2147483629), UINT64_C(2147483587)
    };
    for (size_t i = 0; i < sizeof(primes) / sizeof(primes[0]); i++)
        if (ml2_stress_rank_mod_prime(output, primes[i]) == 4)
            return 1;
    return 0;
}

typedef struct {
    uint64_t base_failures;
    uint64_t retry_failures;
    uint64_t recovered;
    uint64_t fast_path_mismatches;
    uint64_t base_invalid_rank4;
    uint64_t retry_invalid_rank4;
    int max_input_bits;
} ml2_stress_counts_t;

static int
ml2_stress_dimension(int d,
                     uint32_t samples,
                     ml2_stress_counts_t *counts,
                     const quat_alg_t *alg)
{
    ibz_mat_4x4_t target;
    ibz_mat_4x4_init(&target);
    ml2_test_set_target_hnf(&target);

    for (uint32_t sample = 0; sample < samples; sample++) {
        ibz_vec_4_t generators[ML2_TEST_MAX_GENERATORS];
        ibz_vec_4_t base_output[4], retry_output[4];
        for (int i = 0; i < d; i++)
            ibz_vec_4_init(&generators[i]);
        for (int i = 0; i < 4; i++) {
            ibz_vec_4_init(&base_output[i]);
            ibz_vec_4_init(&retry_output[i]);
        }

        ml2_stress_build_generators(generators, d, &target);
        for (int i = 0; i < d; i++) {
            for (int j = 0; j < 4; j++) {
                int bits = ibz_bitsize(&generators[i][j]);
                if (bits > counts->max_input_bits)
                    counts->max_input_bits = bits;
            }
        }

        int base_rho = quat_ml2(base_output, 4, generators, d, alg);
        int retry_rho = quat_ml2_retry(retry_output, 4, generators, d, alg);
        if (base_rho != 4)
            counts->base_failures++;
        if (retry_rho != 4)
            counts->retry_failures++;
        if (base_rho != 4 && retry_rho == 4)
            counts->recovered++;
        if (base_rho == 4 &&
            (retry_rho != 4 ||
             !ml2_test_vector_arrays_identical(base_output, retry_output, 4)))
            counts->fast_path_mismatches++;
        if (base_rho == 4 &&
            !ml2_stress_reported_basis_is_full_rank(base_output))
            counts->base_invalid_rank4++;
        if (retry_rho == 4 &&
            !ml2_stress_reported_basis_is_full_rank(retry_output))
            counts->retry_invalid_rank4++;

        for (int i = 0; i < 4; i++) {
            ibz_vec_4_finalize(&retry_output[i]);
            ibz_vec_4_finalize(&base_output[i]);
        }
        for (int i = 0; i < d; i++)
            ibz_vec_4_finalize(&generators[i]);
    }

    ibz_mat_4x4_finalize(&target);
    return counts->fast_path_mismatches != 0 ||
           counts->base_invalid_rank4 != 0 ||
           counts->retry_invalid_rank4 != 0;
}

int
quat_test_ml2_stress(uint32_t samples)
{
    static const int dimensions[] = { 4, 8, 16 };
    const uint64_t seed = UINT64_C(0x6d6c325f73747273);
    int failed = 0;
    quat_alg_t alg;

    quat_alg_init_set_ui(&alg, 367);
    ml2_stress_prng_state = seed;
    printf("ML2_STRESS_V1 seed=0x%016llx samples_per_d=%u "
           "coefficient_bit_bands=12,55,80,IBZ_BITS/4,IBZ_BITS/2-16(+0..7)\n",
           (unsigned long long)seed,
           samples);
    printf("d,samples,base_failures,retry_residual_failures,recovered,"
           "base_failure_ppm,retry_failure_ppm,fast_path_mismatches,"
           "base_invalid_rank4,retry_invalid_rank4,max_input_bits\n");

    for (size_t i = 0; i < sizeof(dimensions) / sizeof(dimensions[0]); i++) {
        ml2_stress_counts_t counts = { 0 };
        int d = dimensions[i];
        failed |= ml2_stress_dimension(d, samples, &counts, &alg);
        printf("%d,%u,%llu,%llu,%llu,%llu,%llu,%llu,%llu,%llu,%d\n",
               d,
               samples,
               (unsigned long long)counts.base_failures,
               (unsigned long long)counts.retry_failures,
               (unsigned long long)counts.recovered,
               (unsigned long long)(counts.base_failures * UINT64_C(1000000) /
                                    samples),
               (unsigned long long)(counts.retry_failures * UINT64_C(1000000) /
                                    samples),
               (unsigned long long)counts.fast_path_mismatches,
               (unsigned long long)counts.base_invalid_rank4,
               (unsigned long long)counts.retry_invalid_rank4,
               counts.max_input_bits);
    }

    quat_alg_finalize(&alg);
    return failed;
}

/* The compact O*x + N*O constructor reduces its relative generators modulo N
 * before ML2.  Compare its lattice with a small exact-HNF fixture, then add a
 * very large N-multiple to x and check that the represented ideal is exactly
 * unchanged. */
static int
ml2_test_ideal_construction_mod_N(void)
{
    int failed = 0;
    quat_alg_t alg;
    quat_lattice_t order, expected;
    quat_alg_elem_t gamma, lifted_gamma;
    quat_left_ideal_t compact, lifted;
    ibz_t N, lift;

    quat_alg_init_set_ui(&alg, 367);
    quat_lattice_init(&order);
    quat_lattice_init(&expected);
    quat_alg_elem_init(&gamma);
    quat_alg_elem_init(&lifted_gamma);
    quat_left_ideal_init(&compact);
    quat_left_ideal_init(&lifted);
    ibz_init(&N);
    ibz_init(&lift);
    quat_lattice_O0_set(&order);

    ibz_set(&gamma.coord[0], 219);
    ibz_set(&gamma.coord[1], 200);
    ibz_set(&gamma.coord[2], 78);
    ibz_set(&gamma.coord[3], -1);
    ibz_set(&N, 31);

    ibz_set(&expected.denom, 2);
    ibz_mat_4x4_zero(&expected.basis);
    ibz_set(&expected.basis[0][0], 62);
    ibz_set(&expected.basis[1][1], 62);
    ibz_set(&expected.basis[0][2], 2);
    ibz_set(&expected.basis[1][2], 1);
    ibz_set(&expected.basis[2][2], 1);
    ibz_set(&expected.basis[0][3], 61);
    ibz_set(&expected.basis[1][3], 2);
    ibz_set(&expected.basis[3][3], 1);

    if (!quat_lideal_create_with_norm(&compact, &gamma, &N, &order, &alg) ||
        compact.parent_order != &order ||
        ibz_cmp(&compact.norm, &N) != 0 ||
        !quat_lattice_equal(&compact.lattice, &expected)) {
        printf("[ideal_mod_N] FAIL: compact lattice differs from exact HNF fixture\n");
        failed = 1;
        goto cleanup;
    }

    for (int i = 0; i < 4; i++)
        ibz_copy(&lifted_gamma.coord[i], &gamma.coord[i]);
    ibz_copy(&lifted_gamma.denom, &gamma.denom);
    ibz_set(&lift, 1);
    ibz_mul_2exp(&lift, &lift, 160);
    ibz_mul(&lift, &lift, &N);
    ibz_add(&lifted_gamma.coord[0], &lifted_gamma.coord[0], &lift);

    if (!quat_lideal_create_with_norm(&lifted, &lifted_gamma, &N, &order, &alg) ||
        !quat_lattice_equal(&compact.lattice, &lifted.lattice)) {
        printf("[ideal_mod_N] FAIL: adding an N*O element changed the ideal\n");
        failed = 1;
    }

cleanup:
    ibz_finalize(&lift);
    ibz_finalize(&N);
    quat_left_ideal_finalize(&lifted);
    quat_left_ideal_finalize(&compact);
    quat_alg_elem_finalize(&lifted_gamma);
    quat_alg_elem_finalize(&gamma);
    quat_lattice_finalize(&expected);
    quat_lattice_finalize(&order);
    quat_alg_finalize(&alg);
    return failed;
}

int
quat_test_ml2_correctness(void)
{
    int failed = 0;
    printf("\nRunning ML2 exact-span and failure-publication tests\n");
    failed |= ml2_test_weighted_gram_and_precision();
    failed |= ml2_test_zero_and_dependent_dimension(4);
    failed |= ml2_test_zero_and_dependent_dimension(5);
    failed |= ml2_test_zero_and_dependent_dimension(8);
    failed |= ml2_test_zero_and_dependent_dimension(16);
    failed |= ml2_test_span_d8();
    failed |= ml2_test_span_d16_high_dynamic();
    failed |= ml2_test_retry_recovery_and_nonpublication();
    failed |= ml2_test_addition_and_failure_nonpublication();
    failed |= ml2_test_multiplication_alias_and_nonpublication();
    failed |= ml2_test_ideal_construction_mod_N();
#if defined(SQISIGN_ML2_PROFILE)
    failed |= ml2_test_profile_accounting();
#endif
    if (!failed)
        printf("  All ML2 correctness tests PASS\n");
    return failed;
}
